### ISSUE TITLE
doing init <url> - The filename, directory name, or volume label syntax is incorrect.

### ISSUE THREAD

**Issue by pierre-vo** [ing-bank/doing-cli#67]
Command: `doing init https://dev.azure.com/<org>/<proj>/_workitems/edit/1234567`
log:
```
az boards work-item show --id 1234567 --org 'https://dev.azure.com/<org>' --query
'fields.["System.AreaPath","System.IterationPath","System.IterationLevel2"]'
The filename, directory name, or volume label syntax is incorrect.
```

I redacted the identification bits.

- windows 10, running from a PS console
- Python 3.7.4
- doing-cli, version 1.2

I had to use `az login --allow-no-subscriptions` to not have auth error messages.

If I use the az command from the log directly, I get:
```
[
  null,
  null,
  null
]
```

If I remove the `--query` part, I see json data where I can find the fields from the query:
```
{
  "fields": {
    "System.AreaPath": "<data>",
    "System.IterationLevel2": "<data>",
    "System.IterationPath": "<data>",
  }
}
```
which seems to match the query.

`--query 'commentVersionRef.["version"]''` works.
`--query 'fields.["System.AreaPath"]'` returns [null].

Could the dot in the name of the key be the problem?

I used `--query 'fields.["System.AreaPath"]'` from the MINGW64 console and it is working :)
but I still get the error message about the filename when using `doing init` from it.

**Comment by timvink** [comment]
Hee @pierre-vo , thanks for taking the time to report this.

It seems it's a quotation-escaping issue in powershell ([link](https://docs.microsoft.com/en-us/cli/azure/use-cli-effectively#using-quotation-marks-in-values), [link](https://github.com/Azure/azure-cli/blob/dev/doc/quoting-issues-with-powershell.md))

For `doing init`, I just removed the `--query` part and retrieved the data from the json using python. It saves mere milliseconds and no more shell compatibility issues. Will release soon.

I went through the other commands used in other places, and I think it's good (uses single quotes). I'm on macos, let me know if you run into any other issues on powershell!

Regarding the auth error messages, the [docs state](https://docs.microsoft.com/en-us/cli/azure/reference-index?view=azure-cli-latest#az_login):

```
--allow-no-subscriptions
Support access tenants without subscriptions. It's uncommon but useful to run tenant level commands, such as 'az ad'.
```

Did you try `az login` without `--allow-no-subscriptions` ? Do you know why this might work in your case? I might want to update the connection problems troubleshooting page in the `doing` documentation.

**Comment by timvink** [comment]
Released the fix in [v1.2.1](https://github.com/ing-bank/doing-cli/releases/tag/v1.2.1)

**Comment by pierre-vo** [comment]
Thanks! Upgrade ran properly and I am now on doing-cli, version 1.2.1

I have the same error message without the query part:

```
doing init https://dev.azure.com/<org>/RnD/_workitems/edit/XXXXXXX/
az boards work-item show --id XXXXXXX --org 'https://dev.azure.com/<org>'
The filename, directory name, or volume label syntax is incorrect.
```

I was using powershell and mingw in windows terminal, I tried the usual "old" windows cmd and the normal powershell gui and the result is the same.

I filled in the .doing-cli-config.yml manually and tried:

```
$ doing list
az boards query --wiql "SELECT
[System.Id],[System.Title],[System.AssignedTo],[System.WorkItemType],[System.State],[System.CreatedDate]FROM WorkItems
WHERE [System.AreaPath] = '<proj>\<area-path-01>\<area-path-02>' AND [System.IterationPath] UNDER '<proj>\<iter-path-01>' AND
[System.State] IN ('Active', 'New', 'To Do', 'Doing', 'Approved', 'Committed', 'Proposed') ORDER BY
[System.CreatedDate] asc" --org "<org>" -p "<proj>"
The system cannot find the path specified.
```

I copied the command to try it direcly and it failed as well, I had to replace <org> with https://dev.azure.com/<org> and it worked.

```
az --version
azure-cli                         2.25.0

core                              2.25.0
telemetry                          1.0.6

Extensions:
azure-devops                      0.18.0
interactive                        0.4.4

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\<user>\.azure\cliextensions'

Python (Windows) 3.8.9 (tags/v3.8.9:a743f81, Apr  6 2021, 13:22:56) [MSC v.1928 32 bit (Intel)]
```

This was unexpected, az is not using the python version I installed but another one.

Not directly related: I had some weird error messages with the login about an invalid grant, using `az login` and `az devops login` did not help, but `az account clear` before doing the login fixed it.

I thought I had some extra error messages when using `az` directly yesterday, but I did another `az login` wihtout `--allow-no-subscription` to day and all seem fine.  Maybe I got mixed up with the invalid grant error.

**Comment by pierre-vo** [comment]
If I were to clone the repo, would it be possible for me to add some prints/debug messages in some places that would show the possible escaping that powershell does not like?

**Comment by timvink** [comment]
Yes, you can install an editable version like so:

```bash
git clone git@github.com:ing-bank/doing-cli.git
cd doing-cli
pip install -e . 
```

Perhaps you wont need to though, as I built a verbose mode for debugging (see https://ing-bank.github.io/doing-cli/config/config_file/#optional-parameters) that prints out all commands being run by `doing`:

```bash
export DOING_CONFIG_VERBOSE_SHELL=true
doing init <url>
```

Trying to isolate the error:
- I understand that  simple `az boards work-item show --id XXXXXXX` works? And `az boards work-item show --id XXXXXXX --org 'https://dev.azure.com/<org>'` also? That means that the error is with `doing-cli` not with `az`.
- If `doing init <url>` doesn't work, it must be the format of the command, or how I run it using `subprocess`. I'd have to dive deeper into powershell specifics.

In the meantime, you use use a bash emulator for windows, like https://gitforwindows.org/, to get going.

**Comment by pierre-vo** [comment]
Thanks, I tried the verbose shell and do not see any problem in the information shown.

* I understand that simple `az boards work-item show --id XXXXXXX` works?
  * yes, I see the json data
*  And `az boards work-item show --id XXXXXXX --org 'https://dev.azure.com/<org>'` also?
  * yes

I had attempted to use az in some of my scripts as well, I copied some of your commands to give it a try and it goes through.

I use `out_str = subprocess.check_output(az_cmd, shell=True).decode('cp1252')`. I am not familiar enough with subprocess to know if  that makes a big difference with subprocess.run.

**Comment by timvink** [comment]
Ok, we're getting closer. Thanks for the debugging, I don't have powershell myself so can't test with it..

Going to try two things:

1) Change the input to `subprocess.run` to a string instead of list, as suggested here: https://stackoverflow.com/a/24954642/5525118. I will include that in the next release, as it works locally without a problem.
2) Figure out the encoding used. I suspect this might be the real culprit, causing powershell to interpret the command as a filepath and giving you the error. I noticed you used the `cp1252` encoding. Can you try the following in a python shell started via powershell?

```python
from doing.utils import is_wsl
is_wsl() # probably return false, not running in windows subsystem for linux

# if is_wsl() is false, that means doing will use sys.stdout.encoding
import sys
sys.stdout.encoding # does this return 'cp1252' ? If not, we probably have the root cause
```

Btw, next release will also print the encoding used when a command failed to run, for easier debugging.
If the encoding detection is wrong, next up is to detect if python is running without powershell. Can you try

```python
from doing.utils import shell_output
shell_output("echo $host.Name")
```

If the output for you is 'ConsoleHost', ([link](https://devblogs.microsoft.com/scripting/powertip-determine-if-running-in-powershell-console/)) I can write a function to detect powershell and set correct encoding.

another possible way to detect powershell is [link](https://stackoverflow.com/a/59459612/5525118):

```python
import psutil
parent_pid = os.getppid()
print(psutil.Process(parent_pid).name()) # what is the output of this? for me it's 'zsh'
```

If all that fails, but `cp1252` encoding does work for you, then I might choose to write a little encoding detection by trying out a `hello world` command and cycling through encodings until it works. encoding issues.. so much fun :P

**Comment by pierre-vo** [comment]
Maybe I should just get WSL :)

Thank you for taking the time to look into my situation.

```
PS P:\> python
Python 3.7.4 (default, Aug  9 2019, 18:22:51) [MSC v.1915 32 bit (Intel)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from doing.utils import in_wsl
>>> in_wsl()
False
>>> import sys
>>> sys.stdout.encoding
'utf-8'
```

I'm actually quite surprised, I tried in windows-terminal, the normal powershell terminal and the normal cmd terminal.

I use mostly python for small tools on the side, nothing very clean. I started using `cp1252` as it seemed to be what I needed when I switched to python 3 and I have been copying it since then without re-assessing.

```
>>> from doing.utils import shell_output
>>> shell_output("echo $host.Name")
'$host.Name'
```
It does not seem PS is doing any processing on the content here, I quickly checked directly just in case:

```
PS > echo $host.Name
ConsoleHost
```
I also tried `shell_output("echo %PATH%")` and this worked. Even though PS does not handle it, so it looks like this part feeds commands to cmd.exe.

```
>>> import psutil
>>> parent_pid = os.getppid()
>>> print(psutil.Process(parent_pid).name())
powershell.exe
```
That one seems to work. It gives `cmd.exe` from the normal old windows cmd. From MINGW/git bash it gives `bash.exe`.

**Comment by pierre-vo** [comment]
Removing the list and forcing the encoding to `cp1251` seems to help:
```python
    process = subprocess.run(
        ' '.join([command]),
        stdin=subprocess.PIPE,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        universal_newlines=True,
        encoding='cp1252',
        shell=True,
    )
```

```
> doing list
... quite a lot of stuff happening
ERROR: az repos pr list: ''active'' is not a valid value for '--status'. Allowed values: all, active, completed,
abandoned.
Did you mean 'active' ?
```

If I leave the encoding as it was:
```python
az boards query --wiql "SELECT ...." --org ... 
Exception in thread Thread-1:
Traceback (most recent call last):
  File "c:\app\miniconda3\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "c:\app\miniconda3\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "c:\app\miniconda3\lib\subprocess.py", line 1238, in _readerthread
    buffer.append(fh.read())
  File "c:\app\miniconda3\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 8960: invalid continuation byte
```

I thought my escaping in doing-cli-config was bad so I double the \\ and got the same message.
It is weird that my terminal says utf-8 but somehow has problems decoding it afterwards.

**Comment by timvink** [comment]
Alright, we're getting close! I just released [v1.2.2](https://github.com/ing-bank/doing-cli/releases/tag/v1.2.2). This release:

- passes the commands as string to `subprocess.run`
- auto-detects powershell and sets encoding accordingly. On errors, it will also show encoding used.
- removes the quotes around 'active', because you `az repos pr list --status active` is also valid.

Now, I suspect we will have addressed the original error on `doing init`: `The filename, directory name, or volume label syntax is incorrect.`. Let me know :) 

Some commands might still be malformed for powershell and could raise new errors. Let me know and we can see if we can address them.

**Comment by timvink** [comment]
@pierre-vo I'm quite curious to hear if we managed to solve the problem. Can you try the latest version?

**Comment by pierre-vo** [comment]
@timvink sorry for the delay.

I had installed with `pip install -e .` so I fetched 1.2.4 and ran it again.

```
> doing init https://dev.azure.com/myorg/nyproj/_workitems/edit/xxxxxx
There was an error. Ran the following command with encoding 'utf-8':
az boards work-item show --id xxxxxx --org 'https://dev.azure.com/myorg'
ERROR: --organization must be specified. The value should be the URI of your Azure DevOps organization, for example:
https://dev.azure.com/MyOrganization/ or your Azure DevOps Server organization. You can set a default value by running:
az devops configure --defaults organization=https://dev.azure.com/MyOrganization/. For auto detection to work (--detect
true), you must be in a local Git directory that has a "remote" referencing a Azure DevOps or Azure DevOps Server
repository.
```

Trying to run ```az boards work-item show --id xxxxxx --org 'https://dev.azure.com/myorg'``` directly gives me the same message.
Running ```az boards work-item show --id xxxxxx --org "https://dev.azure.com/myorg"``` works.

I replaced some `f" ... '{organization}' ..."` with `f' ... "{organization}" ...'` and the doing init command worked!

I tried `doing list` afterwards:

```
>doing list
Exception in thread Thread-1:
Traceback (most recent call last):
  File "c:\app\miniconda3\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "c:\app\miniconda3\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "c:\app\miniconda3\lib\subprocess.py", line 1238, in _readerthread
    buffer.append(fh.read())
  File "c:\app\miniconda3\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x96 in position 127262: invalid start byte
```

```python
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ C:\App\Miniconda3\Scripts\doing-script.py:33 in <module>                                         │
│                                                                                                  │
│   30                                                                                             │
│   31 if __name__ == '__main__':                                                                  │
│   32 │   sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])                       │
│ ❱ 33 │   sys.exit(load_entry_point('doing-cli', 'console_scripts', 'doing')())                   │
│   34                                                                                             │
│                                                                                                  │
│ c:\app\miniconda3\lib\site-packages\click\core.py:1137 in __call__                               │
│                                                                                                  │
│   1134 │                                                                                         │
│   1135 │   def __call__(self, *args: t.Any, **kwargs: t.Any) -> t.Any:                           │
│   1136 │   │   """Alias for :meth:`main`."""                                                     │
│ ❱ 1137 │   │   return self.main(*args, **kwargs)                                                 │
│   1138                                                                                           │
│   1139                                                                                           │
│   1140 class Command(BaseCommand):                                                               │
│                                                                                                  │
│ c:\app\miniconda3\lib\site-packages\click\core.py:1062 in main                                   │
│                                                                                                  │
│   1059 │   │   try:                                                                              │
│   1060 │   │   │   try:                                                                          │
│   1061 │   │   │   │   with self.make_context(prog_name, args, **extra) as ctx:                  │
│ ❱ 1062 │   │   │   │   │   rv = self.invoke(ctx)                                                 │
│   1063 │   │   │   │   │   if not standalone_mode:                                               │
│   1064 │   │   │   │   │   │   return rv                                                         │
│   1065 │   │   │   │   │   # it's not safe to `ctx.exit(rv)` here!                               │
│                                                                                                  │
│ c:\app\miniconda3\lib\site-packages\click\core.py:1668 in invoke                                 │
│                                                                                                  │
│   1665 │   │   │   │   super().invoke(ctx)                                                       │
│   1666 │   │   │   │   sub_ctx = cmd.make_context(cmd_name, args, parent=ctx)                    │
│   1667 │   │   │   │   with sub_ctx:                                                             │
│ ❱ 1668 │   │   │   │   │   return _process_result(sub_ctx.command.invoke(sub_ctx))               │
│   1669 │   │                                                                                     │
│   1670 │   │   # In chain mode we create the contexts step by step, but after the                │
│   1671 │   │   # base command has been invoked.  Because at that point we do not                 │
│                                                                                                  │
│ c:\app\miniconda3\lib\site-packages\click\core.py:1404 in invoke                                 │
│                                                                                                  │
│   1401 │   │   │   echo(style(message, fg="red"), err=True)                                      │
│   1402 │   │                                                                                     │
│   1403 │   │   if self.callback is not None:                                                     │
│ ❱ 1404 │   │   │   return ctx.invoke(self.callback, **ctx.params)                                │
│   1405 │                                                                                         │
│   1406 │   def shell_complete(self, ctx: Context, incomplete: str) -> t.List["CompletionItem"]:  │
│                                                                                                  │
│ c:\app\miniconda3\lib\site-packages\click\core.py:763 in invoke                                  │
│                                                                                                  │
│    760 │   │                                                                                     │
│    761 │   │   with augment_usage_errors(__self):                                                │
│    762 │   │   │   with ctx:                                                                     │
│ ❱  763 │   │   │   │   return __callback(*args, **kwargs)                                        │
│    764 │                                                                                         │
│    765 │   def forward(                                                                          │
│    766 │   │   __self, __cmd: "Command", *args: t.Any, **kwargs: t.Any  # noqa: B902             │
│                                                                                                  │
│        \doing-cli\src\doing\list\commands.py:78 in list                                          │
│                                                                                                  │
│   75 │   │   )                                                                                   │
│   76 │   │   click.launch(f"{organization}/{project}/_workitems/?_a=query&wiql={quote(query)}    │
│   77 │   else:                                                                                   │
│ ❱ 78 │   │   cmd_list(assignee, author, label, state, type=type, **get_common_options())         │
│   79                                                                                             │
│                                                                                                  │
│        \doing-cli\src\doing\list\_list.py:75 in cmd_list                                         │
│                                                                                                  │
│    72 │   author = replace_user_aliases(author)                                                  │
│    73 │                                                                                          │
│    74 │   query = work_item_query(assignee, author, label, state, area, iteration, type)         │
│ ❱  75 │   work_items = run_command(f'az boards query --wiql "{query}" --org "{organization}" -   │
│    76 │                                                                                          │
│    77 │   if len(work_items) == 0:                                                               │
│    78 │   │   msg = f"[dark_orange3]>[/dark_orange3] No issues in sprint '{iteration}' given f   │
│                                                                                                  │
│        \doing-cli\src\doing\utils.py:234 in run_command                                          │
│                                                                                                  │
│   231 │   │   universal_newlines=True,                                                           │
│   232 │   │   encoding=encoding,                                                                 │
│   233 │   │   shell=True,                                                                        │
│ ❱ 234 │   │   timeout=15,                                                                        │
│   235 │   )                                                                                      │
│   236 │                                                                                          │
│   237 │   if process.returncode != 0:                                                            │
│                                                                                                  │
│ c:\app\miniconda3\lib\subprocess.py:474 in run                                                   │
│                                                                                                  │
│    471 │                                                                                         │
│    472 │   with Popen(*popenargs, **kwargs) as process:                                          │
│    473 │   │   try:                                                                              │
│ ❱  474 │   │   │   stdout, stderr = process.communicate(input, timeout=timeout)                  │
│    475 │   │   except TimeoutExpired:                                                            │
│    476 │   │   │   process.kill()                                                                │
│    477 │   │   │   stdout, stderr = process.communicate()                                        │
│                                                                                                  │
│ c:\app\miniconda3\lib\subprocess.py:939 in communicate                                           │
│                                                                                                  │
│    936 │   │   │   │   endtime = None                                                            │
│    937 │   │   │                                                                                 │
│    938 │   │   │   try:                                                                          │
│ ❱  939 │   │   │   │   stdout, stderr = self._communicate(input, endtime, timeout)               │
│    940 │   │   │   except KeyboardInterrupt:                                                     │
│    941 │   │   │   │   # https://bugs.python.org/issue25942                                      │
│    942 │   │   │   │   # See the detailed comment in .wait().                                    │
│                                                                                                  │
│ c:\app\miniconda3\lib\subprocess.py:1288 in _communicate                                         │
│                                                                                                  │
│   1285 │   │   │                                                                                 │
│   1286 │   │   │   # All data exchanged.  Translate lists into strings.                          │
│   1287 │   │   │   if stdout is not None:                                                        │
│ ❱ 1288 │   │   │   │   stdout = stdout[0]                                                        │
│   1289 │   │   │   if stderr is not None:                                                        │
│   1290 │   │   │   │   stderr = stderr[0]                                                        │
│   1291                                                                                           │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
IndexError: list index out of range
```

Thanks again for your time :)

**Comment by timvink** [comment]
It's hard to work on this, as I cannot replicate it on my system. I installed powershell on mac, and that works without any problems.

### problem 1: detecting the right encoding

It's strange the encoding detected is still `utf-8`, while it should be `cp1252`. Can you try in your terminal to:

```python
python
from doing.utils import guess_shell_encoding
print(guess_shell_encoding())
```

The easiest solution is just specifying the encoding in the `.doing-cli-config.yml` file, an option that I added now in v1.2.8

### problem 2:

It seems quoting is still an issue. I went ahead and replaced all single quotes with escaped double quotes (`\"`). Also released in v1.2.8.

I would say, give the latest release another try :) https://github.com/ing-bank/doing-cli/releases

**Comment by timvink** [comment]
@pierre-vo care to give it another whirl? :)

**Comment by timvink** [comment]
@pierre-vo another reminder? Would like to tackle this issue :)
